### ISSUE TITLE
Incorrect Merkle Proof in Diagram in Rebased Merkle Tree

### ISSUE THREAD

**Issue by ropats16** [ArweaveTeam/examples#2]
In section 2 Merkle Trees of Rebased Merkle Trees, in the main diagram for the section, the Merkle Proof shown for chunk 3 needs to be revised to "id2/"id3" instead of "id2/ id2".

https://github.com/ArweaveTeam/examples/blob/main/rebased_merkle_tree/README.md#2-merkle-trees

**Comment by JamesPiechota** [comment]
Thanks for logging!
